backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"  # Folder for uploaded images
public_folder: "/images/uploads"  # Public path for images on your live site
collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Content", widget: "markdown" }
