backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"  # Images will go here
collections:
  - name: "news"
    label: "News"
    folder: "news"             # News posts saved here
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Content", widget: "markdown" }
